In [1]:
import requests as rq

from bs4 import BeautifulSoup as bs 

import pandas as pd

pd.set_option('display.max_rows', None)

In [2]:
url='https://es.wikipedia.org/wiki/MasterChef_Espa%C3%B1a'

In [3]:
html=rq.get(url).content
soup=bs(html, 'html.parser')

In [4]:
tabla=soup.find_all('table')[4]

In [5]:
filas=tabla.find_all('tr')

filas=[f.text.strip().split('\n') for f in filas]

filas[:5]

[['Nombre[26]\u200b', 'Procedencia', 'Edad', 'Ocupación', 'Información'],
 ['Juan Manuel Sánchez',
  '',
  ' Almería',
  '',
  '26',
  '',
  'Camarero',
  '',
  'Ganador[27]\u200b'],
 ['Eva M. Millán',
  '',
  ' Córdoba',
  '',
  '32',
  '',
  'Bióloga y nutricionista',
  '',
  '2.ª finalista[28]\u200b'],
 ['Fabián León',
  '',
  ' Mallorca',
  '',
  '18',
  '',
  'Estudiante de Publicidad',
  '',
  '3.er finalista'],
 ['José David Moliner',
  '',
  ' Valencia',
  '',
  '33',
  '',
  'Ingeniero informático',
  '',
  '13.er expulsado']]

In [6]:
final=[]

for f in filas:
    
    tmp=[]
    
    for palabra in f:
        
        if palabra!='':
            
            tmp.append(palabra)
            
    final.append(tmp)
    
final[:5]

[['Nombre[26]\u200b', 'Procedencia', 'Edad', 'Ocupación', 'Información'],
 ['Juan Manuel Sánchez', ' Almería', '26', 'Camarero', 'Ganador[27]\u200b'],
 ['Eva M. Millán',
  ' Córdoba',
  '32',
  'Bióloga y nutricionista',
  '2.ª finalista[28]\u200b'],
 ['Fabián León',
  ' Mallorca',
  '18',
  'Estudiante de Publicidad',
  '3.er finalista'],
 ['José David Moliner',
  ' Valencia',
  '33',
  'Ingeniero informático',
  '13.er expulsado']]

In [7]:
col_names=final[0]

data=final[1:]

edicion1=pd.DataFrame(data, columns=col_names)

In [8]:
edicion1.columns =['nombre', 'procedencia', 'edad', 'ocupacion', 'ranking']

In [9]:
edicion1['edicion']='1'
edicion1['sexo']='F'

In [10]:
edicion1.loc[0,'sexo'] = 'M'
edicion1.loc[1,'sexo'] = 'F'
edicion1.loc[2,'sexo'] = 'M'
edicion1.loc[3,'sexo'] = 'M'
edicion1.loc[4,'sexo'] = 'F'
edicion1.loc[5,'sexo'] = 'M'
edicion1.loc[6,'sexo'] = 'F'
edicion1.loc[7,'sexo'] = 'F'
edicion1.loc[8,'sexo'] = 'M'
edicion1.loc[9,'sexo'] = 'M'
edicion1.loc[10,'sexo'] = 'F'
edicion1.loc[11,'sexo'] = 'M'
edicion1.loc[12,'sexo'] = 'F'
edicion1.loc[13,'sexo'] = 'M'
edicion1.loc[14,'sexo'] = 'F'

In [11]:
edicion1.loc[0,'ranking'] = '1'
edicion1.loc[1,'ranking'] = '2'
edicion1.loc[2,'ranking'] = '3'
edicion1.loc[3,'ranking'] = '4'
edicion1.loc[4,'ranking'] = '5'
edicion1.loc[5,'ranking'] = '6'
edicion1.loc[6,'ranking'] = '7'
edicion1.loc[7,'ranking'] = '8'
edicion1.loc[8,'ranking'] = '9'
edicion1.loc[9,'ranking'] = '10'
edicion1.loc[10,'ranking'] = '11'
edicion1.loc[11,'ranking'] = '12'
edicion1.loc[12,'ranking'] = '13'
edicion1.loc[13,'ranking'] = '14'
edicion1.loc[14,'ranking'] = '15'

In [12]:
tabla=soup.find_all('table')[8]


filas=tabla.find_all('tr')

filas=[f.text.strip().split('\n') for f in filas]

filas[:5]


final=[]

for f in filas:
    
    tmp=[]
    
    for palabra in f:
        
        if palabra!='':
            
            tmp.append(palabra)
            
    final.append(tmp)
    
final[:5]


col_names=final[0]

data=final[1:]

edicion2=pd.DataFrame(data, columns=col_names)

In [13]:
edicion2.columns =['nombre', 'procedencia', 'edad', 'ocupacion', 'ranking']

In [14]:
edicion2['edicion']='2'
edicion2['sexo']='F'

In [15]:
edicion2.loc[0,'sexo'] = 'F'
edicion2.loc[1,'sexo'] = 'M'
edicion2.loc[2,'sexo'] = 'M'
edicion2.loc[3,'sexo'] = 'M'
edicion2.loc[4,'sexo'] = 'F'
edicion2.loc[5,'sexo'] = 'F'
edicion2.loc[6,'sexo'] = 'F'
edicion2.loc[7,'sexo'] = 'F'
edicion2.loc[8,'sexo'] = 'M'
edicion2.loc[9,'sexo'] = 'F'
edicion2.loc[10,'sexo'] = 'M'
edicion2.loc[11,'sexo'] = 'M'
edicion2.loc[12,'sexo'] = 'F'
edicion2.loc[13,'sexo'] = 'M'
edicion2.loc[14,'sexo'] = 'F'

In [16]:
edicion2.loc[0,'ranking'] = '1'
edicion2.loc[1,'ranking'] = '2'
edicion2.loc[2,'ranking'] = '3'
edicion2.loc[3,'ranking'] = '4'
edicion2.loc[4,'ranking'] = '5'
edicion2.loc[5,'ranking'] = '6'
edicion2.loc[6,'ranking'] = '7'
edicion2.loc[7,'ranking'] = '8'
edicion2.loc[8,'ranking'] = '9'
edicion2.loc[9,'ranking'] = '10'
edicion2.loc[10,'ranking'] = '11'
edicion2.loc[11,'ranking'] = '12'
edicion2.loc[12,'ranking'] = '13'
edicion2.loc[13,'ranking'] = '14'
edicion2.loc[14,'ranking'] = '15'

In [17]:
tabla=soup.find_all('table')[12]


filas=tabla.find_all('tr')

filas=[f.text.strip().split('\n') for f in filas]

filas[:5]


final=[]

for f in filas:
    
    tmp=[]
    
    for palabra in f:
        
        if palabra!='':
            
            tmp.append(palabra)
            
    final.append(tmp)
    
final[:5]


col_names=final[0]

data=final[1:]

edicion3=pd.DataFrame(data, columns=col_names)

In [18]:
edicion3.columns =['nombre', 'procedencia', 'edad', 'ocupacion', 'ranking']

In [19]:
edicion3['edicion']='3'
edicion3['sexo']='F'

In [20]:
edicion3.loc[0,'sexo'] = 'M'
edicion3.loc[1,'sexo'] = 'F'
edicion3.loc[2,'sexo'] = 'F'
edicion3.loc[3,'sexo'] = 'M'
edicion3.loc[4,'sexo'] = 'M'
edicion3.loc[5,'sexo'] = 'F'
edicion3.loc[6,'sexo'] = 'F'
edicion3.loc[7,'sexo'] = 'M'
edicion3.loc[8,'sexo'] = 'M'
edicion3.loc[9,'sexo'] = 'M'
edicion3.loc[10,'sexo'] = 'F'
edicion3.loc[11,'sexo'] = 'F'
edicion3.loc[12,'sexo'] = 'F'
edicion3.loc[13,'sexo'] = 'F'
edicion3.loc[14,'sexo'] = 'M'

In [21]:
edicion3.loc[0,'ranking'] = '1'
edicion3.loc[1,'ranking'] = '2'
edicion3.loc[2,'ranking'] = '3'
edicion3.loc[3,'ranking'] = '4'
edicion3.loc[4,'ranking'] = '5'
edicion3.loc[5,'ranking'] = '6'
edicion3.loc[6,'ranking'] = '7'
edicion3.loc[7,'ranking'] = '8'
edicion3.loc[8,'ranking'] = '9'
edicion3.loc[9,'ranking'] = '10'
edicion3.loc[10,'ranking'] = '11'
edicion3.loc[11,'ranking'] = '12'
edicion3.loc[12,'ranking'] = '13'
edicion3.loc[13,'ranking'] = '14'
edicion3.loc[14,'ranking'] = '15'

In [22]:
tabla=soup.find_all('table')[16]


filas=tabla.find_all('tr')

filas=[f.text.strip().split('\n') for f in filas]

filas[:5]


final=[]

for f in filas:
    
    tmp=[]
    
    for palabra in f:
        
        if palabra!='':
            
            tmp.append(palabra)
            
    final.append(tmp)
    
final[:5]


col_names=final[0]

data=final[1:]

edicion4=pd.DataFrame(data, columns=col_names)

In [23]:
edicion4.columns =['nombre', 'procedencia', 'edad', 'ocupacion', 'ranking']

In [24]:
edicion4['edicion']='4'
edicion4['sexo']='F'

In [25]:
edicion4.loc[0,'sexo'] = 'F'
edicion4.loc[1,'sexo'] = 'M'
edicion4.loc[2,'sexo'] = 'M'
edicion4.loc[3,'sexo'] = 'F'
edicion4.loc[4,'sexo'] = 'F'
edicion4.loc[5,'sexo'] = 'M'
edicion4.loc[6,'sexo'] = 'F'
edicion4.loc[7,'sexo'] = 'M'
edicion4.loc[8,'sexo'] = 'F'
edicion4.loc[9,'sexo'] = 'M'
edicion4.loc[10,'sexo'] = 'F'
edicion4.loc[11,'sexo'] = 'M'
edicion4.loc[12,'sexo'] = 'F'
edicion4.loc[13,'sexo'] = 'M'
edicion4.loc[14,'sexo'] = 'F'
edicion4.loc[15,'sexo'] = 'F'

In [26]:
edicion4.loc[0,'ranking'] = '1'
edicion4.loc[1,'ranking'] = '2'
edicion4.loc[2,'ranking'] = '3'
edicion4.loc[3,'ranking'] = '4'
edicion4.loc[4,'ranking'] = '5'
edicion4.loc[5,'ranking'] = '6'
edicion4.loc[6,'ranking'] = '7'
edicion4.loc[7,'ranking'] = '8'
edicion4.loc[8,'ranking'] = '9'
edicion4.loc[9,'ranking'] = '10'
edicion4.loc[10,'ranking'] = '11'
edicion4.loc[11,'ranking'] = '12'
edicion4.loc[12,'ranking'] = '13'
edicion4.loc[13,'ranking'] = '14'
edicion4.loc[14,'ranking'] = '15'
edicion4.loc[15,'ranking'] = '16'

In [27]:
tabla=soup.find_all('table')[20]


filas=tabla.find_all('tr')

filas=[f.text.strip().split('\n') for f in filas]

filas[:5]


final=[]

for f in filas:
    
    tmp=[]
    
    for palabra in f:
        
        if palabra!='':
            
            tmp.append(palabra)
            
    final.append(tmp)
    
final[:5]


col_names=final[0]

data=final[1:]

edicion5=pd.DataFrame(data, columns=col_names)

In [28]:
edicion5.columns =['nombre', 'procedencia', 'edad', 'ocupacion', 'ranking']

In [29]:
edicion5['edicion']='5'
edicion5['sexo']='F'

In [30]:
edicion5.loc[0,'sexo'] = 'M'
edicion5.loc[1,'sexo'] = 'M'
edicion5.loc[2,'sexo'] = 'F'
edicion5.loc[3,'sexo'] = 'F'
edicion5.loc[4,'sexo'] = 'F'
edicion5.loc[5,'sexo'] = 'F'
edicion5.loc[6,'sexo'] = 'M'
edicion5.loc[7,'sexo'] = 'M'
edicion5.loc[8,'sexo'] = 'F'
edicion5.loc[9,'sexo'] = 'M'
edicion5.loc[10,'sexo'] = 'F'
edicion5.loc[11,'sexo'] = 'M'
edicion5.loc[12,'sexo'] = 'F'
edicion5.loc[13,'sexo'] = 'M'
edicion5.loc[14,'sexo'] = 'F'
edicion5.loc[15,'sexo'] = 'M'

In [31]:
edicion5.loc[0,'ranking'] = '1'
edicion5.loc[1,'ranking'] = '2'
edicion5.loc[2,'ranking'] = '3'
edicion5.loc[3,'ranking'] = '4'
edicion5.loc[4,'ranking'] = '5'
edicion5.loc[5,'ranking'] = '6'
edicion5.loc[6,'ranking'] = '7'
edicion5.loc[7,'ranking'] = '8'
edicion5.loc[8,'ranking'] = '9'
edicion5.loc[9,'ranking'] = '10'
edicion5.loc[10,'ranking'] = '11'
edicion5.loc[11,'ranking'] = '12'
edicion5.loc[12,'ranking'] = '13'
edicion5.loc[13,'ranking'] = '14'
edicion5.loc[14,'ranking'] = '15'
edicion5.loc[15,'ranking'] = '16'

In [32]:
tabla=soup.find_all('table')[24]


filas=tabla.find_all('tr')

filas=[f.text.strip().split('\n') for f in filas]

filas[:5]


final=[]

for f in filas:
    
    tmp=[]
    
    for palabra in f:
        
        if palabra!='':
            
            tmp.append(palabra)
            
    final.append(tmp)
    
final[:5]


col_names=final[0]

data=final[1:]

edicion6=pd.DataFrame(data, columns=col_names)

In [33]:
edicion6.columns =['nombre', 'procedencia', 'edad', 'ocupacion', 'ranking']

In [34]:
edicion6['edicion']='6'
edicion6['sexo']='F'

In [35]:
edicion6.loc[0,'sexo'] = 'F'
edicion6.loc[1,'sexo'] = 'F'
edicion6.loc[2,'sexo'] = 'F'
edicion6.loc[3,'sexo'] = 'M'
edicion6.loc[4,'sexo'] = 'M'
edicion6.loc[5,'sexo'] = 'F'
edicion6.loc[6,'sexo'] = 'M'
edicion6.loc[7,'sexo'] = 'M'
edicion6.loc[8,'sexo'] = 'M'
edicion6.loc[9,'sexo'] = 'M'
edicion6.loc[10,'sexo'] = 'F'
edicion6.loc[11,'sexo'] = 'M'
edicion6.loc[12,'sexo'] = 'F'
edicion6.loc[13,'sexo'] = 'F'
edicion6.loc[14,'sexo'] = 'M'

In [36]:
edicion6.loc[0,'ranking'] = '1'
edicion6.loc[1,'ranking'] = '2'
edicion6.loc[2,'ranking'] = '3'
edicion6.loc[3,'ranking'] = '4'
edicion6.loc[4,'ranking'] = '5'
edicion6.loc[5,'ranking'] = '6'
edicion6.loc[6,'ranking'] = '7'
edicion6.loc[7,'ranking'] = '8'
edicion6.loc[8,'ranking'] = '9'
edicion6.loc[9,'ranking'] = '10'
edicion6.loc[10,'ranking'] = '11'
edicion6.loc[11,'ranking'] = '12'
edicion6.loc[12,'ranking'] = '13'
edicion6.loc[13,'ranking'] = '14'
edicion6.loc[14,'ranking'] = '15'

In [37]:
tabla=soup.find_all('table')[28]


filas=tabla.find_all('tr')

filas=[f.text.strip().split('\n') for f in filas]

filas[:5]


final=[]

for f in filas:
    
    tmp=[]
    
    for palabra in f:
        
        if palabra!='':
            
            tmp.append(palabra)
            
    final.append(tmp)
    
final[:5]


col_names=final[0]

data=final[1:]

edicion7=pd.DataFrame(data, columns=col_names)

In [38]:
edicion7.columns =['nombre', 'procedencia', 'edad', 'ocupacion', 'ranking']

In [39]:
edicion7['edicion']='7'
edicion7['sexo']='F'

In [40]:
edicion7.loc[0,'sexo'] = 'M'
edicion7.loc[1,'sexo'] = 'F'
edicion7.loc[2,'sexo'] = 'M'
edicion7.loc[3,'sexo'] = 'F'
edicion7.loc[4,'sexo'] = 'M'
edicion7.loc[5,'sexo'] = 'F'
edicion7.loc[6,'sexo'] = 'F'
edicion7.loc[7,'sexo'] = 'F'
edicion7.loc[8,'sexo'] = 'F'
edicion7.loc[9,'sexo'] = 'M'
edicion7.loc[10,'sexo'] = 'M'
edicion7.loc[11,'sexo'] = 'M'
edicion7.loc[12,'sexo'] = 'F'
edicion7.loc[13,'sexo'] = 'F'
edicion7.loc[14,'sexo'] = 'F'
edicion7.loc[15,'sexo'] = 'M'

In [41]:
edicion7.loc[0,'ranking'] = '1'
edicion7.loc[1,'ranking'] = '2'
edicion7.loc[2,'ranking'] = '3'
edicion7.loc[3,'ranking'] = '4'
edicion7.loc[4,'ranking'] = '5'
edicion7.loc[5,'ranking'] = '6'
edicion7.loc[6,'ranking'] = '7'
edicion7.loc[7,'ranking'] = '8'
edicion7.loc[8,'ranking'] = '9'
edicion7.loc[9,'ranking'] = '10'
edicion7.loc[10,'ranking'] = '11'
edicion7.loc[11,'ranking'] = '12'
edicion7.loc[12,'ranking'] = '13'
edicion7.loc[13,'ranking'] = '14'
edicion7.loc[14,'ranking'] = '15'
edicion7.loc[15,'ranking'] = '16'

In [42]:
tabla=soup.find_all('table')[32]


filas=tabla.find_all('tr')

filas=[f.text.strip().split('\n') for f in filas]

filas[:5]


final=[]

for f in filas:
    
    tmp=[]
    
    for palabra in f:
        
        if palabra!='':
            
            tmp.append(palabra)
            
    final.append(tmp)
    
final[:5]


col_names=final[0]

data=final[1:]

edicion8=pd.DataFrame(data, columns=col_names)

In [43]:
edicion8.columns =['nombre', 'procedencia', 'edad', 'ocupacion', 'ranking']

In [44]:
edicion8['edicion']='8'
edicion8['sexo']='F'

In [45]:
edicion8.loc[0,'sexo'] = 'F'
edicion8.loc[1,'sexo'] = 'M'
edicion8.loc[2,'sexo'] = 'M'
edicion8.loc[3,'sexo'] = 'M'
edicion8.loc[4,'sexo'] = 'F'
edicion8.loc[5,'sexo'] = 'M'
edicion8.loc[6,'sexo'] = 'F'
edicion8.loc[7,'sexo'] = 'M'
edicion8.loc[8,'sexo'] = 'F'
edicion8.loc[9,'sexo'] = 'M'
edicion8.loc[10,'sexo'] = 'F'
edicion8.loc[11,'sexo'] = 'F'
edicion8.loc[12,'sexo'] = 'M'
edicion8.loc[13,'sexo'] = 'F'
edicion8.loc[14,'sexo'] = 'F'
edicion8.loc[15,'sexo'] = 'F'
edicion8.loc[16,'sexo'] = 'F'
edicion8.loc[17,'sexo'] = 'M'

In [46]:
edicion8.loc[0,'ranking'] = '1'
edicion8.loc[1,'ranking'] = '2'
edicion8.loc[2,'ranking'] = '3'
edicion8.loc[3,'ranking'] = '4'
edicion8.loc[4,'ranking'] = '5'
edicion8.loc[5,'ranking'] = '6'
edicion8.loc[6,'ranking'] = '7'
edicion8.loc[7,'ranking'] = '8'
edicion8.loc[8,'ranking'] = '9'
edicion8.loc[9,'ranking'] = '10'
edicion8.loc[10,'ranking'] = '11'
edicion8.loc[11,'ranking'] = '12'
edicion8.loc[12,'ranking'] = '13'
edicion8.loc[13,'ranking'] = '14'
edicion8.loc[14,'ranking'] = '15'
edicion8.loc[15,'ranking'] = '16'
edicion8.loc[16,'ranking'] = '17'
edicion8.loc[17,'ranking'] = '18'

In [47]:
tabla=soup.find_all('table')[36]


filas=tabla.find_all('tr')

filas=[f.text.strip().split('\n') for f in filas]

filas[:5]


final=[]

for f in filas:
    
    tmp=[]
    
    for palabra in f:
        
        if palabra!='':
            
            tmp.append(palabra)
            
    final.append(tmp)
    
final[:5]


col_names=final[0]

data=final[1:]

edicion9=pd.DataFrame(data, columns=col_names)

In [48]:
edicion9.columns =['nombre', 'procedencia', 'edad', 'ocupacion', 'ranking']

In [49]:
edicion9['edicion']='9'
edicion9['sexo']='F'

In [50]:
edicion8.loc[0,'sexo'] = 'M'
edicion8.loc[1,'sexo'] = 'F'
edicion8.loc[2,'sexo'] = 'F'
edicion8.loc[3,'sexo'] = 'M'
edicion8.loc[4,'sexo'] = 'F'
edicion8.loc[5,'sexo'] = 'M'
edicion8.loc[6,'sexo'] = 'M'
edicion8.loc[7,'sexo'] = 'F'
edicion8.loc[8,'sexo'] = 'F'
edicion8.loc[9,'sexo'] = 'M'
edicion8.loc[10,'sexo'] = 'M'
edicion8.loc[11,'sexo'] = 'F'
edicion8.loc[12,'sexo'] = 'F'
edicion8.loc[13,'sexo'] = 'M'
edicion8.loc[14,'sexo'] = 'M'
edicion8.loc[15,'sexo'] = 'M'

In [51]:
edicion9.loc[0,'ranking'] = '1'
edicion9.loc[1,'ranking'] = '2'
edicion9.loc[2,'ranking'] = '3'
edicion9.loc[3,'ranking'] = '4'
edicion9.loc[4,'ranking'] = '5'
edicion9.loc[5,'ranking'] = '6'
edicion9.loc[6,'ranking'] = '7'
edicion9.loc[7,'ranking'] = '8'
edicion9.loc[8,'ranking'] = '9'
edicion9.loc[9,'ranking'] = '10'
edicion9.loc[10,'ranking'] = '11'
edicion9.loc[11,'ranking'] = '12'
edicion9.loc[12,'ranking'] = '13'
edicion9.loc[13,'ranking'] = '14'
edicion9.loc[14,'ranking'] = '15'
edicion9.loc[15,'ranking'] = '16'

In [52]:
todas_ediciones=pd.concat([edicion1, edicion2, edicion3, edicion4, edicion5, edicion6, edicion7, edicion8, edicion9], axis=0)

In [53]:
todas_ediciones.head()

,nombre,procedencia,edad,ocupacion,ranking,edicion,sexo
0,Juan Manuel Sánchez,Almería,26,Camarero,1,1,M
1,Eva M. Millán,Córdoba,32,Bióloga y nutricionista,2,1,F
2,Fabián León,Mallorca,18,Estudiante de Publicidad,3,1,M
3,José David Moliner,Valencia,33,Ingeniero informático,4,1,M
4,Maribel Gil,Castellón,59,Ama de casa,5,1,F

In [54]:
todas_ediciones.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 142 entries, 0 to 15
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nombre       142 non-null    object
 1   procedencia  142 non-null    object
 2   edad         142 non-null    object
 3   ocupacion    142 non-null    object
 4   ranking      142 non-null    object
 5   edicion      142 non-null    object
 6   sexo         142 non-null    object
dtypes: object(7)
memory usage: 8.9+ KB

In [55]:
todas_ediciones['edad'] = todas_ediciones['edad'].astype('int')
todas_ediciones['ranking'] = todas_ediciones['ranking'].astype('int')
todas_ediciones['edicion'] = todas_ediciones['edicion'].astype('int')

In [56]:
todas_ediciones.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 142 entries, 0 to 15
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nombre       142 non-null    object
 1   procedencia  142 non-null    object
 2   edad         142 non-null    int32
 3   ocupacion    142 non-null    object
 4   ranking      142 non-null    int32
 5   edicion      142 non-null    int32
 6   sexo         142 non-null    object
dtypes: int32(3), object(4)
memory usage: 7.2+ KB

In [57]:
todas_ediciones = todas_ediciones.reset_index()
todas_ediciones.head()

,index,nombre,procedencia,edad,ocupacion,ranking,edicion,sexo
0,0,Juan Manuel Sánchez,Almería,26,Camarero,1,1,M
1,1,Eva M. Millán,Córdoba,32,Bióloga y nutricionista,2,1,F
2,2,Fabián León,Mallorca,18,Estudiante de Publicidad,3,1,M
3,3,José David Moliner,Valencia,33,Ingeniero informático,4,1,M
4,4,Maribel Gil,Castellón,59,Ama de casa,5,1,F

In [58]:
todas_ediciones.drop('index', inplace=True, axis=1)

In [59]:
todas_ediciones.head()

,nombre,procedencia,edad,ocupacion,ranking,edicion,sexo
0,Juan Manuel Sánchez,Almería,26,Camarero,1,1,M
1,Eva M. Millán,Córdoba,32,Bióloga y nutricionista,2,1,F
2,Fabián León,Mallorca,18,Estudiante de Publicidad,3,1,M
3,José David Moliner,Valencia,33,Ingeniero informático,4,1,M
4,Maribel Gil,Castellón,59,Ama de casa,5,1,F

In [60]:
todas_ediciones['ocupacion2']=todas_ediciones['ocupacion']

In [61]:
ocupacion2_list = todas_ediciones['ocupacion2'].tolist()

In [62]:
todas_ediciones.ocupacion2.replace(['Camarero',
 'Bióloga y nutricionista',
 'Estudiante de Publicidad',
 'Ingeniero informático',
 'Ama de casa',
 'Soldador',
 'Estudiante de Economía',
 'Maquilladora y esteticista',
 'Policía Foral',
 'Administrador de ingresos',
 'Ama de casa',
 'Estudiante de CAF',
 'Asistente administrativo',
 'Ingeniero de Telecomunicaciones',
 'Estudiante de Derecho',
 'Carnicera en paro',
 'Estudiante de Historia del Arte',
 'Camarero',
 'Realizador de publicidad',
 'Ingeniera de sonido y DJ',
 'Empresaria',
 'Dependienta',
 'Ex asistente de dirección',
 'Profesor de Yoga',
 'Técnico de radioterapia',
 'Doctor en Biología molecular',
 'Oficial funerario',
 'Ama de casa',
 'Arquitecto',
 'Estudiante de Ciencias Ambientales',
 'Vendedor ambulante',
 'Auxiliar de óptica',
 'Estudiante de Odontología y modelo',
 'Técnico de laboratorio',
 'Camarero y modelo',
 'Nutricionista',
 'Empresaria de calzado',
 'Camarero',
 'Campeón y maestro de artes marciales',
 'Empresario de ambientadores',
 'Voluntaria de ONG',
 'Jubilada',
 'Protésico dental',
 'Profesora de infantil',
 'Estudiante de Medicina',
 'Ama de casa',
 'Friegaplatos',
 'Pintor industrial',
 'Empresaria',
 'Ama de casa',
 'Estudiante de CAFD',
 'Modelo y periodista',
 'Ingeniero de estructuras',
 'Camarera',
 'Empresario',
 'Teleoperadora',
 'Estudiante de Enfermería',
 'Desempleada',
 'Auxiliar administrativo',
 'Ama de casa',
 'Profesora y atleta',
 'Exfutbolista profesional',
 'Jefe de sala',
 'Jubilada',
 'Policía Nacional',
 'Bloguera',
 'Panadera',
 'Diseñador de moda',
 'Banderillero',
 'Modelo profesional',
 'Emprendedor de negocios',
 'Abogada',
 'Camarero',
 'Peluquera y maquilladora',
 'Peluquero',
 'Psicóloga',
 'Delegado comercial',
 'Estudiante de Nutrición',
 'Dietista',
 'Empleada de hogar',
 'Community manager',
 'Bombero',
 'Estudiante de Turismo',
 'Ingeniero de telecomunicaciones',
 'Hostelero',
 'Financiero',
 'Periodista',
 'Comerciante',
 'Conductor de autobuses',
 'Comercial',
 'Jubilada',
 'Bodeguero',
 'Pescadero',
 'Fotógrafa',
 'Emprendedor',
 'Recursos Humanos',
 'Empresario',
 'Ama de casa',
 'Dependienta',
 'Diseñadora de lápidas',
 'Empleada del hogar',
 'Cerrajero forense',
 'Camarero',
 'Economista jubilado',
 'Ama de casa',
 'Comercial de informática',
 'Ingeniera mecánica',
 'Estadístico',
 'Empresaria de joyas',
 'Abogado',
 'Entrenador personal',
 'Exjugador y entrenador de fútbol sala',
 'Profesora de yoga',
 'Empresario y músico',
 'Conserje de comunidad de vecinos',
 'Profesor de Inglés',
 'Economista',
 'Comercial de tabaco',
 'Directora de tienda nupcial',
 'Farmacéutica',
 'Músico',
 'Educadora social',
 'Comandante del Ejército del Aire',
 'Limpiadora y camarera',
 'Directora de Marketing',
 'Empleado de tanatorio',
 'Comercial de grifos',
 'Fisioterapeuta y estudiante de Medicina',
 'Coordinadora de eventos',
 'Camarero',
 'Emprendedora de marketing hípico',
 'Cardiólogo',
 'Jugador profesional de póquer',
 'Estudiante de Farmacia y Nutrición',
 'Responsable de desarrollo de negocio',
 'Empresario hostelero',
 'Músico',
 'Directora de marketing y publicidad',
 'Guardia Civil',
 'Gestor deportivo',
 'Estudiante de Restauración',
 'Abogado jubilado'],
                                   
                                   
                                   
                                   

['Hostelería',
 'Salud',
 'Estudiante',
 'Ingeniería',
 'Ama/o de casa',
 'Oficio manual',
 'Estudiante',
 'Belleza',
 'Defensa',
 'Administrativo/a',
 'Ama/o de casa',
 'Estudiante',
 'Administrativo/a',
 'Ingeniería',
 'Estudiante',
 'Oficio alimentación',
 'Estudiante',
 'Hostelería',
 'Publicidad y márqueting',
 'Ingeniería',
 'Empresario/a',
 'Moda',
 'Administrativo/a',
 'Yoga o artes marciales',
 'Salud',
 'Salud',
 'Tanatorio',
 'Ama/o de casa',
 'Arquitectura',
 'Estudiante',
 'Vendedor ambulante',
 'Salud',
 'Estudiante',
 'Salud',
 'Hostelería',
 'Salud',
 'Empresario/a',
 'Hostelería',
 'Yoga o artes marciales',
 'Empresario/a',
 'Social',
 'Jubilado/a',
 'Salud',
 'Profesor/a',
 'Estudiante',
 'Ama/o de casa',
 'Hostelería',
 'Oficio manual',
 'Empresario/a',
 'Ama/o de casa',
 'Estudiante',
 'Periodista',
 'Ingeniería',
 'Hostelería',
 'Empresario/a',
 'Comercial',
 'Estudiante',
 'Paro',
 'Administrativo/a',
 'Ama/o de casa',
 'Profesor/a',
 'Deporte',
 'Hostelería',
 'Jubilado/a',
 'Defensa',
 'Influencer',
 'Oficio alimentación',
 'Diseñador/a',
 'Banderillero',
 'Modelo',
 'Empresario/a',
 'Abogacía',
 'Hostelería',
 'Belleza',
 'Belleza',
 'Psicología',
 'Comercial',
 'Estudiante',
 'Salud',
 'Empleada de hogar',
 'Community manager',
 'Defensa',
 'Estudiante',
 'Ingeniería',
 'Hostelería',
 'Finanzas',
 'Periodista',
 'Comercial',
 'Oficio manual',
 'Comercial',
 'Jubilado/a',
 'Influencer',
 'Oficio alimentación',
 'Fotografía',
 'Empresario/a',
 'RRHH',
 'Empresario/a',
 'Amo/a de casa',
 'Moda',
 'Diseñador/a',
 'Empleada del hogar',
 'Oficio manual',
 'Hostelería',
 'Jubilado/a',
 'Ama/o de casa',
 'Comercial',
 'Ingeniería',
 'Estadístico',
 'Empresario/a',
 'Abogacía',
 'Deporte',
 'Deporte',
 'Yoga o artes marciales',
 'Empresario/a',
 'Conserje',
 'Profesor/a',
 'Economista',
 'Comercial',
 'Moda',
 'Salud',
 'Música',
 'Social',
 'Defensa',
 'Hostelería',
 'Publicidad y márqueting',
 'Tanatorio',
 'Comercial',
 'Salud',
 'Eventos',
 'Hostelería',
 'Emprendedor/a',
 'Salud',
 'Póquer',
 'Estudiante',
 'Negocio',
 'Empresario/a',
 'Música',
 'Publicidad y márqueting',
 'Defensa',
 'Deporte',
 'Estudiante',
 'Jubilado/a'],inplace=True)

In [63]:
todas_ediciones.ocupacion2.unique()

array(['Hostelería', 'Salud', 'Estudiante', 'Ingeniería', 'Ama/o de casa',
       'Oficio manual', 'Belleza', 'Defensa', 'Administrativo/a',
       'Oficio alimentación', 'Publicidad y márqueting', 'Empresario/a',
       'Moda', 'Yoga o artes marciales', 'Tanatorio', 'Arquitectura',
       'Vendedor ambulante', 'Social', 'Jubilado/a', 'Profesor/a',
       'Periodista', 'Comercial', 'Paro', 'Deporte', 'Influencer',
       'Diseñador/a', 'Banderillero', 'Modelo', 'Abogacía', 'Psicología',
       'Empleada de hogar', 'Community manager', 'Finanzas', 'Fotografía',
       'RRHH', 'Empleada del hogar', 'Estadístico', 'Conserje',
       'Economista', 'Música', 'Eventos', 'Emprendedor/a', 'Póquer',
       'Negocio'], dtype=object)

In [64]:
todas_ediciones.head()

,nombre,procedencia,edad,ocupacion,ranking,edicion,sexo,ocupacion2
0,Juan Manuel Sánchez,Almería,26,Camarero,1,1,M,Hostelería
1,Eva M. Millán,Córdoba,32,Bióloga y nutricionista,2,1,F,Salud
2,Fabián León,Mallorca,18,Estudiante de Publicidad,3,1,M,Estudiante
3,José David Moliner,Valencia,33,Ingeniero informático,4,1,M,Ingeniería
4,Maribel Gil,Castellón,59,Ama de casa,5,1,F,Ama/o de casa

In [65]:
todas_ediciones.to_excel(r'C:\Users\alexd\Ironhack\Proyectos\Project4_DA_Ironhack\Data\masterchef.xls', index=False)

C:\Users\alexd\AppData\Local\Temp/ipykernel_14416/3048578067.py:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  todas_ediciones.to_excel(r'C:\Users\alexd\Ironhack\Proyectos\Project4_DA_Ironhack\Data\masterchef.xls', index=False)

In [66]:
todas_ediciones.to_csv(r'C:\Users\alexd\Ironhack\Proyectos\Project4_DA_Ironhack\Data\masterchef.csv', index=False)

In [67]:
from sqlalchemy import create_engine

In [68]:
str_conn='mysql+pymysql://root:password@127.0.0.1:3306/project4'

cursor=create_engine(str_conn)

In [69]:
todas_ediciones.to_sql(name='masterchef', con=cursor, if_exists='replace', index=False)

In [330]:
info1=pd.read_clipboard()

In [331]:
info1

,PD,PEX,PEL,PI,PEX.1,PEL.1,PI.1,PEX.2,PEL.2,PI.2,...,1​.1,PEL.9,PI.8,PP.1,PEL.10,PI.9,PEX.8,PEL.11,PI.10,DF
0,1,Juan,Manuel,ENT,EP,MD,MD,EP,MD,SMD,...,GD,AD,IN,BD,GD,IN,GD,IN,GD,GANADOR
1,2,Eva,ENT,EP,MD,SMD,EP,IN,GD,EG,...,AD,IN,DD,AD,IN,SMD,BD,GD,SMD,DUELISTA
2,3,Fabián,ENT,EG,IN,BD,EP,MD,MD,EG,...,BD,SPD,BD,AD,MD,BD,GD,IN,EL,None
3,4,José,David,ENT,EP,GD,AD,EP,SPD,AD,...,MD,BD,GD,BD,AD,MD,BD,MD,EL,None
4,5,Maribel,ENT,EP,BD,MD,EG,IN,MD,EP,...,AD,IN,BD,AD,EL,None,None,None,None,None
5,6,Cerezo,ENT,EG,IN,MD,EP,GD,MD,EP,...,BD,EL,None,None,None,None,None,None,None,None
6,7,Clara,ENT,EG,IN,GD,EP,IN,MD,EG,...,None,None,None,None,None,None,None,None,None,None
7,8,María,ENT,EG,IN,MD,EP,IN,BD,EP,...,None,None,None,None,None,None,None,None,None,None
8,9,José,Luis,ENT,EP,MD,MD,EG,IN,MD,...,None,None,None,None,None,None,None,None,None,None
9,10,Noé,ENT,EP,MD,MD,EP,MD,BD,EP,...,None,None,None,None,None,None,None,None,None,None
10,11,Santiaga,ENT,EG,IN,BD,EG,IN,MD,EP,...,None,None,None,None,None,None,None,None,None,None
11,12,Efrén,ENT,EG,IN,MD,EP,IN,AD,EG,...,None,None,None,None,None,None,None,None,None,None
12,13,Nati,ENT,EP,SPD,BD,EG,IN,MD,EG,...,None,None,None,None,None,None,None,None,None,None
13,14,Juanma,ENT,EG,IN,MD,EP,EL,None,None,...,None,None,None,None,None,None,None,None,None,None
14,15,Paloma,ENT,EP,EL,BD,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [332]:
info1['edicion']='1'
info1=info1.rename(columns = {'PD':'ranking'})

In [333]:
info2=pd.read_clipboard()

In [334]:
info2

,PD,PI,PEX,PEL,PI.1,PEX.1,PEL.1,PI.2,PEX.2,PEL.2,...,PEX.9,PEL.10,PI.10,PEXn.1,1​.1,PEL.11,PI.11,PEX.10,PEL.12,DF
0,1,Vicky,ENT,MD,EP,MD,GD,EP,MD,SMD,...,GD,EG,IN,GD,AD,IN,GD,BD,GD,GANADORA
1,2,Mateo,ENT,MD,EP,AD,MD,EP,MD,GD,...,SMD,EP,MD,BD,AD,IN,SMD,GD,IN,DUELISTA
2,3,Cristóbal,ENT,BD,EP,IN,MD,EP,SPD,MD,...,BD,MD,SPD,MD,EL,None,None,None,None,None
3,4,Emil,ENT,GD,EP,IN,MD,EP,BD,AD,...,AD,EG,IN,BD,BD,MD,EL,None,None,None
4,5,Lorena,ENT,MD,EP,SPD,SMD,EP,MD,MD,...,None,None,None,None,None,None,None,None,None,None
5,6,Cristina,ENT,AD,EP,IN,MD,EP,BD,MD,...,BD,EP,EL,None,None,None,None,None,None,None
6,7,Milagrosa,ENT,SMD,EP,AD,BD,EP,MD,MD,...,None,None,None,None,None,None,None,None,None,None
7,8,Marina,ENT,MD,EP,IN,BD,EP,BD,MD,...,None,None,None,None,None,None,None,None,None,None
8,9,Gonzalo,ENT,MD,EP,IN,BD,EP,MD,MD,...,None,None,None,None,None,None,None,None,None,None
9,10,Celia,ENT,MD,EP,AD,MD,EP,BD,MD,...,None,None,None,None,None,None,None,None,None,None
10,11,Jorge,ENT,MD,EP,IN,MD,EP,MD,MD,...,None,None,None,None,None,None,None,None,None,None
11,12,Miguel,Ángel,ENT,MD,EP,IN,BD,EP,BD,...,None,None,None,None,None,None,None,None,None,None
12,13,Churra,ENT,MD,EP,MD,MD,EP,MD,MD,...,None,None,None,None,None,None,None,None,None,None
13,14,Daniel,ENT,BD,EP,IN,MD,EP,EL,MD,...,None,None,None,None,None,None,None,None,None,None
14,15,Lola,ENT,BD,EP,EL,BD,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [335]:
info2['edicion']='2'
info2=info2.rename(columns = {'PD':'ranking'})

In [336]:
info3=pd.read_clipboard()

In [337]:
info3

,PD,PI,PEX,PEL,PI.1,PEX.1,PEL.1,PI.2,PEX.2,PEL.2,...,PEL.8,PI.9,PEX.8,PEL.9,PI.10,PEX.9,PEL.10,PI.11,PEX.10,DF
1,Carlos,ENT,GD,EG,IN,AD,EG,IN,GD,EG,...,AD,MD,EG,IN,EG,EG,IN,MD,GD,GANADOR
2,Sally,ENT,MD,EP,MD,GD,EP,AD,MD,EP,...,MD,AD,EG,IN,EP,EG,IN,GD,IN,DUELISTA
3,Andrea,ENT,AD,EP,BD,MD,EP,MD,SMD,EP,...,MD,AD,EP,IN,EG,EP,SPD,MD,EL,None
4,Antonio,ENT,MD,EG,IN,MD,EP,BD,MD,EG,...,MD,MD,EP,GD,EG,EP,GD,MD,EL,None
5,Kevin,ENT,MD,EG,IN,BD,EG,IN,AD,EG,...,SPD,DD,NP,IN,SPD,EP,EL,None,None,None
6,Lidia,ENT,MD,EP,BD,MD,EG,IN,MD,EG,...,AD,AD,EP,SPD,EL,None,None,None,None,None
7,Mila,ENT,MD,EG,IN,MD,EP,AD,MD,EP,...,None,None,None,None,None,None,None,None,None,None
8,Fidel,ENT,MD,EG,IN,MD,EP,MD,MD,EG,...,EL,None,None,None,None,None,None,None,None,None
9,Pablo,ENT,SMD,EP,MD,BD,EP,BD,MD,EP,...,None,None,None,None,None,None,None,None,None,None
10,Víctor,ENT,MD,EG,IN,SMD,EG,IN,MD,EG,...,None,None,None,None,None,None,None,None,None,None
11,Mireia,ENT,AD,EP,BD,MD,EG,IN,MD,EP,...,None,None,None,None,None,None,None,None,None,None
12,Encina,ENT,MD,EG,IN,MD,EG,IN,MD,EG,...,None,None,None,None,None,None,None,None,None,None
13,Raquel,ENT,MD,EG,IN,MD,EG,IN,MD,EP,...,None,None,None,None,None,None,None,None,None,None
14,Sara,ENT,MD,EP,MD,MD,EP,EL,MD,None,...,None,None,None,None,None,None,None,None,None,None
15,Alberto,ENT,AD,EP,EL,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [338]:
info3['edicion']='3'

In [339]:
info3

,PD,PI,PEX,PEL,PI.1,PEX.1,PEL.1,PI.2,PEX.2,PEL.2,...,PI.9,PEX.8,PEL.9,PI.10,PEX.9,PEL.10,PI.11,PEX.10,DF,edicion
1,Carlos,ENT,GD,EG,IN,AD,EG,IN,GD,EG,...,MD,EG,IN,EG,EG,IN,MD,GD,GANADOR,3
2,Sally,ENT,MD,EP,MD,GD,EP,AD,MD,EP,...,AD,EG,IN,EP,EG,IN,GD,IN,DUELISTA,3
3,Andrea,ENT,AD,EP,BD,MD,EP,MD,SMD,EP,...,AD,EP,IN,EG,EP,SPD,MD,EL,None,3
4,Antonio,ENT,MD,EG,IN,MD,EP,BD,MD,EG,...,MD,EP,GD,EG,EP,GD,MD,EL,None,3
5,Kevin,ENT,MD,EG,IN,BD,EG,IN,AD,EG,...,DD,NP,IN,SPD,EP,EL,None,None,None,3
6,Lidia,ENT,MD,EP,BD,MD,EG,IN,MD,EG,...,AD,EP,SPD,EL,None,None,None,None,None,3
7,Mila,ENT,MD,EG,IN,MD,EP,AD,MD,EP,...,None,None,None,None,None,None,None,None,None,3
8,Fidel,ENT,MD,EG,IN,MD,EP,MD,MD,EG,...,None,None,None,None,None,None,None,None,None,3
9,Pablo,ENT,SMD,EP,MD,BD,EP,BD,MD,EP,...,None,None,None,None,None,None,None,None,None,3
10,Víctor,ENT,MD,EG,IN,SMD,EG,IN,MD,EG,...,None,None,None,None,None,None,None,None,None,3
11,Mireia,ENT,AD,EP,BD,MD,EG,IN,MD,EP,...,None,None,None,None,None,None,None,None,None,3
12,Encina,ENT,MD,EG,IN,MD,EG,IN,MD,EG,...,None,None,None,None,None,None,None,None,None,3
13,Raquel,ENT,MD,EG,IN,MD,EG,IN,MD,EP,...,None,None,None,None,None,None,None,None,None,3
14,Sara,ENT,MD,EP,MD,MD,EP,EL,MD,None,...,None,None,None,None,None,None,None,None,None,3
15,Alberto,ENT,AD,EP,EL,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,3

In [340]:
info4=pd.read_clipboard()

In [341]:
info4

,,,PD,PI,PEX,PEL,PI.1,PEX.1,PEL.1,PI.2,PEX.2,PEL.2,...,PEL.8,PI.9,PEX.9,PEL.9,PI.10,PEX.10,PEL.10,PI.11,PEX.11,DF
1,Virginia,ENT,MD,EP,MD,MD,EG,IN,MD,NP,EG,IN,...,IN,DD,EG,IN,MD,AD,IN,GD,IN,GANADORA
2,Ángel,ENT,MD,EG,IN,MD,EP,BD,MD,NP,EP,BD,...,IN,MD,EP,AD,BD,AD,IN,MD,GD,DUELISTA
3,José,Luis,ENT,MD,EP,MD,MD,EG,IN,AD,MD,EP,...,BD,BD,MD,EP,AD,BD,AD,IN,MD,EL
4,Rocío,ENT,BD,EP,MD,MD,EG,IN,AD,GD,EG,IN,...,GD,MD,EG,IN,MD,BD,GD,MD,EL,None
5,Raquel,ENT,AD,EP,IN,MD,EG,IN,MD,NP,EP,AD,...,IN,MD,EG,IN,GD,BD,EL,None,None,None
6,David,ENT,GD,EG,IN,MD,EP,MD,MD,NP,EG,IN,...,None,None,None,None,None,None,None,None,None,None
7,Natalia,ENT,MD,EG,IN,AD,EP,AD,MD,NP,EG,IN,...,EL,None,None,None,None,None,None,None,None,None
8,Pablo,ENT,BD,EG,IN,MD,EP,AD,AD,MD,EG,IN,...,None,None,None,None,None,None,None,None,None,None
9,Reichel,ENT,MD,EG,IN,PIN,EP,IN,MD,NP,EP,AD,...,None,None,None,None,None,None,None,None,None,None
10,Daniel,ENT,MD,EP,MD,MD,EG,IN,AD,SMD,EP,IN,...,None,None,None,None,None,None,None,None,None,None
11,Dania,EL,EG,IN,MD,NP,EG,IN,DG,BD,MD,EP,...,None,None,None,None,None,None,None,None,None,None
12,Juan,ENT,AD,EG,IN,MD,EP,MD,AD,MD,EG,IN,...,None,None,None,None,None,None,None,None,None,None
13,Esmeralda,ENT,MD,EG,IN,MD,EG,BD,MD,NP,EP,EL,...,None,None,None,None,None,None,None,None,None,None
14,Salva,ENT,BD,EG,IN,AD,EP,EL,BD,None,None,None,...,None,None,None,None,None,None,None,None,None,None
15,Emilia,ENT,MD,EP,SPD,AB,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
16,Aniuska,ENT,BD,EP,EL,BD,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [342]:
info4['edicion']='4'
info4=info4.rename(columns = {'PD':'ranking'})

In [345]:
info5=pd.read_clipboard()

In [346]:
info5

,,PD,PEX,PEL,PI,PEX.1,PEL.1,PI.1,PEX.2,PEL.2,PI.2,...,PEX.10,PEL.10,PI.10,PEX.11,n,1​,PEL.11,PI.11,PEX.12,CF
1,Jorge,ENT,EG,IN,MD,EG,IN,SMD,EP,BD,MD,...,AD,SMD,EG,IN,SMD,GD,IN,GD,IN,GANADOR

In [347]:
info5['edicion']='5'
info5=info5.rename(columns = {'PD':'ranking'})

In [348]:
info6=pd.read_clipboard()

In [349]:
info6

,,,,,,PD,PEX,PEL,PI,PEX.1,PEL.1,PI.1,PEX.2,PEL.2,PI.2,...,PI.9,PEXn.1,1​.1,PEL.10,PI.10,PEX.9,PEL.11,PI.11,PEX.10,DF
1,Marta,ENT,EP,BD,GD,AD,EG,IN,AD,EP,MD,AD,EP,EG,IN,...,IN,AD,AD,IN,SMD,BD,SPD,GD,IN,GANADORA
2,Ketty,ENT,EG,IN,SMD,EG,IN,AD,EP,IN,GD,EP,EG,IN,MD,...,BD,MD,AD,IN,MD,GD,DUELISTA,None,None,None
3,Oxana,ENT,EP,AD,IN,MD,EP,AD,SMD,EG,IN,BD,EP,EG,IN,...,SPD,BD,BD,BD,GD,BD,GD,BD,EL,None
4,Toni,ENT,EP,AD,IN,MD,EG,IN,BD,EG,IN,MD,EP,EG,IN,...,GD,MD,AD,IN,SMD,EL,None,None,None,None
5,Daniel,ENT,EP,AD,IN,AD,EP,BD,MD,EP,MD,MD,EP,IN,DP,...,None,None,None,None,None,None,None,None,None,None
6,Sofía,ENT,EG,IN,BD,EG,IN,MD,EG,IN,MD,EP,IN,MD,EG,...,EL,None,None,None,None,None,None,None,None,None
7,Víctor,ENT,EP,AD,IN,BD,EP,BD,GD,EP,GD,MD,EP,EG,IN,...,EL,None,None,None,None,None,None,None,None,None
8,Jon,ENT,EP,BD,SPD,BD,EP,BD,AD,EG,IN,BD,EP,EP,AD,...,None,None,None,None,None,None,None,None,None,None
9,Fabio,ENT,EP,AD,IN,MD,EP,AD,MD,EG,IN,AD,EP,IN,BD,...,None,None,None,None,None,None,None,None,None,None
10,Jorge,ENT,EG,IN,BD,EG,IN,MD,EP,SPD,MD,EP,EP,AD,MD,...,None,None,None,None,None,None,None,None,None,None
11,Marina,ENT,EG,IN,MD,EG,IN,MD,EP,IN,BD,EP,EG,IN,MD,...,None,None,None,None,None,None,None,None,None,None
12,Ramón,ENT,EG,IN,GD,EP,IN,BD,EG,IN,BD,EP,EP,EL,SMD,...,None,None,None,None,None,None,None,None,None,None
13,Eva,ENT,EG,IN,MD,EG,IN,MD,EP,EL,BD,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
14,Loli,ENT,EG,IN,BD,EP,EL,BD,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
15,Fernando,ENT,EP,BD,EL,BD,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [350]:
info6['edicion']='6'
info6=info6.rename(columns = {'PD':'ranking'})

In [351]:
info7=pd.read_clipboard()

In [352]:
info7

,,,,,,,,,PD,PEX,PEL,PI,PEX.1,PEL.1,PI.1,PEX.2,PEL.2,PI.2,...,PEL.9,PI.9,PEX.9,PEL.10,PI.10,PEX.10,PEL.11,PI.11,PEX.11,DF
1,Aleix,JC,ENT,EP,AD,BD,EP,MD,MD,EP,NP,SMD,IN,BD,EG,IN,MD,AD,...,IN,MD,EG,IN,GD,GD,IN,SMD,GD,GANADOR
2,Teresa,SVN,ENT,EP,MD,MD,EG,IN,MD,EP,GD,IN,MD,EP,NP,SMD,IN,BD,...,GD,EP,GD,MD,MD,GD,GD,IN,DUELISTA,None
3,Valentín,JC,ENT,EP,BD,MD,EP,AD,MD,EG,IN,SMD,EG,IN,BD,BD,BD,DG,...,IN,SMD,BD,SPD,MD,EL,None,None,None,None
4,Aitana,JC,ENT,EP,IN,MD,EG,IN,NP,IN,MD,EG,IN,MD,BD,SMD,MD,EG,...,MD,SMD,IN,BD,EL,None,None,None,None,None
5,Carlos,SVN,ENT,EP,AD,BD,EG,IN,MD,EP,IN,BD,EP,GD,IN,MD,AD,IN,...,BD,EL,None,None,None,None,None,None,None,None
6,Samira,PR,EL,ENT,EG,IN,MD,EP,MD,AD,GD,GD,EG,IN,MD,EG,IN,MD,...,None,None,None,None,None,None,None,None,None,None
7,Carmen,SVN,ENT,EP,BD,SMD,EP,MD,MD,EG,IN,MD,EG,IN,BD,BD,GD,DP,...,None,None,None,None,None,None,None,None,None,None
8,Natalia,PR,ENT,EG,IN,MD,EG,IN,MD,EG,IN,BD,EP,NP,GD,IN,BD,BD,...,None,None,None,None,None,None,None,None,None,None
9,Gloria,JC,ENT,EP,MD,MD,EP,AD,MD,EG,IN,MD,EP,IN,MD,AD,IN,DP,...,None,None,None,None,None,None,None,None,None,None
10,Marcos,JC,ENT,EP,AD,MD,EP,IN,MD,EP,BD,NP,GD,BD,EP,NP,BD,GD,...,None,None,None,None,None,None,None,None,None,None
11,Osiris,PR,ENT,EG,IN,GD,EG,AD,MD,EG,NP,GD,IN,BD,EG,IN,MD,BD,...,None,None,None,None,None,None,None,None,None,None
12,Josecho,PR,ENT,EG,IN,MD,EG,IN,GD,EG,IN,BD,EG,IN,MD,AD,AB,None,...,None,None,None,None,None,None,None,None,None,None
13,Laly,SVN,ENT,EP,MD,MD,EP,SPD,DP,EP,IN,GD,EP,BD,NP,EL,BD,None,...,None,None,None,None,None,None,None,None,None,None
14,Alicia,PR,ENT,EG,IN,BD,EG,IN,DP,EP,NP,BD,EL,BD,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
15,Sara,PR,ENT,EG,IN,MD,EP,EL,SMD,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
16,Jeancha,SVN,ENT,EP,EL,BD,NaN,NaN,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [353]:
info7['edicion']='7'
info7=info7.rename(columns = {'PD':'ranking'})

In [355]:
info8=pd.read_clipboard()

In [356]:
info8

,,,PD,PEX,PEL,PI,PEX.1,PEL.1,PI.1,PEX.2,PEL.2,PI.2,...,PI.9,PEX.10,PEL.9,PI.10,PEXn,2​,PEL.10,PI.11,PEX.11,CF
1,Ana,MD,ENT,SMD,AD,IN,AD,EG,IN,SMD,EG,IN,...,EP,GD,IN,GD,EG,IN,GD,BD,IN,GANADORA

In [357]:
info8['edicion']='8'
info8=info8.rename(columns = {'PD':'ranking'})

In [358]:
info9=pd.read_clipboard()

In [359]:
info9

,,,,,,PD,PEX,PEL,PI,PEX.1,PEL.1,PI.1,PEX.2,PEL.2,PI.2,...,PI.9,PEX.10,PEL.10,PI.10,PEXn,1​,PEL.11,PI.11,PEX.11,DF
1,Arnau,ENT,EP,BD,MD,EP,IN,GD,EP,MD,AD,IN,GD,AD,EP,...,GD,MD,EP,GD,SMD,BD,GD,GD,IN,GANADOR
2,Meri,ENT,EG,IN,SMD,EG,IN,AD,EG,IN,MD,NP,EP,AD,MD,...,MD,EG,IN,MD,AD,IN,SMD,GD,DUELISTA,None
3,María,ENT,EP,SMD,GD,EP,GD,MD,EP,MD,MD,SPD,MD,NP,EP,...,SMD,EG,IN,MD,BD,SPD,BD,EL,None,None
4,Fran,ENT,EG,IN,MD,EG,IN,BD,EG,IN,MD,NP,EG,IN,MD,...,IN,GD,BD,IN,MD,EL,None,None,None,None
5,Ofelia,ENT,EP,MD,MD,EP,MD,MD,EP,AD,IN,SMD,AD,EG,IN,...,EP,SPD,MD,MD,EL,None,None,None,None,None
6,José,AB,ENT,SMD,EP,NP,AD,IN,MD,EG,IN,BD,EP,SPD,MD,...,None,None,None,None,None,None,None,None,None,None
7,Toni,ENT,EP,IN,MD,EP,BD,BD,EG,IN,MD,NP,NP,IN,DG,...,None,None,None,None,None,None,None,None,None,None
8,Amelicious,ENT,EP,GD,AD,EG,IN,SMD,EG,IN,MD,NP,EG,IN,MD,...,None,None,None,None,None,None,None,None,None,None
9,Jiaping,ENT,EG,IN,MD,EP,BD,AD,EG,IN,MD,NP,EG,IN,DP,...,None,None,None,None,None,None,None,None,None,None
10,Dani,ENT,EG,IN,MD,EG,IN,AD,EP,AD,IN,MD,NP,EP,MD,...,None,None,None,None,None,None,None,None,None,None
11,Pepe,ENT,EG,IN,MD,EG,IN,MD,EG,IN,MD,NP,EG,AD,MD,...,None,None,None,None,None,None,None,None,None,None
12,Alicia,ENT,EG,IN,MD,EP,MD,MD,EG,IN,MD,NP,EP,MD,AD,...,None,None,None,None,None,None,None,None,None,None
13,Vero,ENT,EG,IN,AD,EG,IN,MD,EP,MD,AD,IN,MD,NP,EP,...,None,None,None,None,None,None,None,None,None,None
14,Álex,ENT,EP,BD,MD,EG,IN,MD,EP,MD,BD,EL,BD,None,None,...,None,None,None,None,None,None,None,None,None,None
15,José,María,ENT,EG,IN,MD,EP,EL,BD,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
16,Jesús,ENT,EP,EL,BD,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [360]:
info9['edicion']='9'
info9=info9.rename(columns = {'PD':'ranking'})

In [365]:
todas_infos=pd.concat([info1, info2, info3, info4, info5, info6, info7, info8, info9], axis=0)

In [366]:
todas_infos

,ranking,PEX,PEL,PI,PEX.1,PEL.1,PI.1,PEX.2,PEL.2,PI.2,...,PI.11,PEX.10,PEL.12,PD,n,PEX.11,PEX.12,CF,PELn,2​
0,1,Juan,Manuel,ENT,EP,MD,MD,EP,MD,SMD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Eva,ENT,EP,MD,SMD,EP,IN,GD,EG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Fabián,ENT,EG,IN,BD,EP,MD,MD,EG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,José,David,ENT,EP,GD,AD,EP,SPD,AD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Maribel,ENT,EP,BD,MD,EG,IN,MD,EP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,Cerezo,ENT,EG,IN,MD,EP,GD,MD,EP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,Clara,ENT,EG,IN,GD,EP,IN,MD,EG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,María,ENT,EG,IN,MD,EP,IN,BD,EP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,José,Luis,ENT,EP,MD,MD,EG,IN,MD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,Noé,ENT,EP,MD,MD,EP,MD,BD,EP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,Santiaga,ENT,EG,IN,BD,EG,IN,MD,EP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,Efrén,ENT,EG,IN,MD,EP,IN,AD,EG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,Nati,ENT,EP,SPD,BD,EG,IN,MD,EG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,Juanma,ENT,EG,IN,MD,EP,EL,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,Paloma,ENT,EP,EL,BD,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,1,ENT,MD,Vicky,MD,GD,EP,MD,SMD,EP,...,GD,BD,GD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,ENT,MD,Mateo,AD,MD,EP,MD,GD,EP,...,SMD,GD,IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,ENT,BD,Cristóbal,IN,MD,EP,SPD,MD,EP,...,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,ENT,GD,Emil,IN,MD,EP,BD,AD,EP,...,EL,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,ENT,MD,Lorena,SPD,SMD,EP,MD,MD,EP,...,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,ENT,AD,Cristina,IN,MD,EP,BD,MD,EP,...,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,ENT,SMD,Milagrosa,AD,BD,EP,MD,MD,EP,...,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,ENT,MD,Marina,IN,BD,EP,BD,MD,EP,...,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,ENT,MD,Gonzalo,IN,BD,EP,MD,MD,EP,...,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,ENT,MD,Celia,AD,MD,EP,BD,MD,EP,...,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,ENT,MD,Jorge,IN,MD,EP,MD,MD,EP,...,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,Ángel,ENT,Miguel,EP,IN,MD,EP,BD,BD,...,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,ENT,MD,Churra,MD,MD,EP,MD,MD,EP,...,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,ENT,BD,Daniel,IN,MD,EP,EL,MD,EP,...,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,ENT,BD,Lola,EL,BD,EP,None,None,None,...,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,GD,EG,ENT,AD,EG,IN,GD,EG,IN,...,MD,GD,NaN,Carlos,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,MD,EP,ENT,GD,EP,MD,MD,EP,AD,...,GD,IN,NaN,Sally,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,AD,EP,ENT,MD,EP,BD,SMD,EP,MD,...,MD,EL,NaN,Andrea,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,MD,EG,ENT,MD,EP,IN,MD,EG,BD,...,MD,EL,NaN,Antonio,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,MD,EG,ENT,BD,EG,IN,AD,EG,IN,...,None,None,NaN,Kevin,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,MD,EP,ENT,MD,EG,BD,MD,EG,IN,...,None,None,NaN,Lidia,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,MD,EG,ENT,MD,EP,IN,MD,EP,AD,...,None,None,NaN,Mila,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,MD,EG,ENT,MD,EP,IN,MD,EG,MD,...,None,None,NaN,Fidel,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,SMD,EP,ENT,BD,EP,MD,MD,EP,BD,...,None,None,NaN,Pablo,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,MD,EG,ENT,SMD,EG,IN,MD,EG,IN,...,None,None,NaN,Víctor,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,AD,EP,ENT,MD,EG,BD,MD,EP,IN,...,None,None,NaN,Mireia,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,MD,EG,ENT,MD,EG,IN,MD,EG,IN,...,None,None,NaN,Encina,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,MD,EG,ENT,MD,EG,IN,MD,EP,IN,...,None,None,NaN,Raquel,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,MD,EP,ENT,MD,EP,MD,MD,None,EL,...,None,None,NaN,Sara,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,AD,EP,ENT,None,None,EL,None,None,None,...,None,None,NaN,Alberto,NaN,NaN,NaN,NaN,NaN,NaN
"(1, Virginia, ENT)",MD,MD,MD,EP,IN,MD,EG,EG,IN,NP,...,GD,AD,NaN,NaN,IN,IN,NaN,NaN,NaN,NaN
"(2, Ángel, ENT)",MD,IN,MD,EG,BD,MD,EP,EP,BD,NP,...,MD,AD,NaN,NaN,IN,GD,NaN,NaN,NaN,NaN
"(3, José, Luis)",ENT,EP,MD,MD,EG,IN,MD,MD,EP,AD,...,IN,BD,NaN,NaN,AD,MD,NaN,NaN,NaN,NaN
"(4, Rocío, ENT)",BD,MD,MD,EP,IN,AD,EG,EG,IN,GD,...,MD,BD,NaN,NaN,IN,EL,NaN,NaN,NaN,NaN
"(5, Raquel, ENT)",AD,IN,MD,EP,IN,MD,EG,EP,AD,NP,...,None,BD,NaN,NaN,GD,None,NaN,NaN,NaN,NaN
"(6, David, ENT)",GD,IN,MD,EG,MD,MD,EP,EG,IN,NP,...,None,None,NaN,NaN,EL,None,NaN,NaN,NaN,NaN
"(7, Natalia, ENT)",MD,IN,AD,EG,AD,MD,EP,EG,IN,NP,...,None,None,NaN,NaN,MD,None,NaN,NaN,NaN,NaN
"(8, Pablo, ENT)",BD,IN,MD,EG,AD,AD,EP,EG,IN,MD,...,None,None,NaN,NaN,IN,None,NaN,NaN,NaN,NaN
"(9, Reichel, ENT)",MD,IN,PIN,EG,IN,MD,EP,EP,AD,NP,...,None,None,NaN,NaN,SMD,None,NaN,NaN,NaN,NaN
"(10, Daniel, ENT)",MD,MD,MD,EP,IN,AD,EG,EP,IN,SMD,...,None,None,NaN,NaN,IN,None,NaN,NaN,NaN,NaN
"(11, Dania, EL)",EG,MD,NP,IN,IN,DG,EG,MD,EP,BD,...,None,None,NaN,NaN,MD,None,NaN,NaN,NaN,NaN
"(12, Juan, ENT)",AD,IN,MD,EG,MD,AD,EP,EG,IN,MD,...,None,None,NaN,NaN,MD,None,NaN,NaN,NaN,NaN
"(13, Esmeralda, ENT)",MD,IN,MD,EG,BD,MD,EG,EP,EL,NP,...,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN
"(14, Salva, ENT)",BD,IN,AD,EG,EL,BD,EP,None,None,None,...,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN
"(15, Emilia, ENT)",MD,SPD,AB,EP,None,None,None,None,None,None,...,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN
"(16, Aniuska, ENT)",BD,EL,BD,EP,None,None,None,None,None,None,...,None,None,NaN,NaN,None,None,NaN,NaN,NaN,NaN
"(1, Jorge)",ENT,EG,IN,MD,EG,IN,SMD,EP,BD,MD,...,GD,AD,NaN,NaN,SMD,IN,IN,GANADOR,NaN,NaN
"(1, Marta, ENT, EP, BD, GD)",AD,EG,IN,AD,EP,MD,AD,EP,EG,IN,...,GD,IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(2, Ketty, ENT, EG, IN, SMD)",EG,IN,AD,EP,IN,GD,EP,EG,IN,MD,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(3, Oxana, ENT, EP, AD, IN)",MD,EP,AD,SMD,EG,IN,BD,EP,EG,IN,...,BD,EL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(4, Toni, ENT, EP, AD, IN)",MD,EG,IN,BD,EG,IN,MD,EP,EG,IN,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(5, Daniel, ENT, EP, AD, IN)",AD,EP,BD,MD,EP,MD,MD,EP,IN,DP,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(6, Sofía, ENT, EG, IN, BD)",EG,IN,MD,EG,IN,MD,EP,IN,MD,EG,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(7, Víctor, ENT, EP, AD, IN)",BD,EP,BD,GD,EP,GD,MD,EP,EG,IN,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(8, Jon, ENT, EP, BD, SPD)",BD,EP,BD,AD,EG,IN,BD,EP,EP,AD,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(9, Fabio, ENT, EP, AD, IN)",MD,EP,AD,MD,EG,IN,AD,EP,IN,BD,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(10, Jorge, ENT, EG, IN, BD)",EG,IN,MD,EP,SPD,MD,EP,EP,AD,MD,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(11, Marina, ENT, EG, IN, MD)",EG,IN,MD,EP,IN,BD,EP,EG,IN,MD,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(12, Ramón, ENT, EG, IN, GD)",EP,IN,BD,EG,IN,BD,EP,EP,EL,SMD,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(13, Eva, ENT, EG, IN, MD)",EG,IN,MD,EP,EL,BD,None,None,None,None,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(14, Loli, ENT, EG, IN, BD)",EP,EL,BD,None,None,None,None,None,None,None,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(15, Fernando, ENT, EP, BD, EL)",BD,None,None,None,None,None,None,None,None,None,...,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"(1, Aleix, JC, ENT, EP, AD, BD, EP, MD)",MD,EP,NP,SMD,IN,BD,EG,IN,MD,AD,...,SMD,GD,NaN,NaN,NaN,GD,NaN,NaN,NaN,NaN
"(2, Teresa, SVN, ENT, EP, MD, MD, EG, IN)",MD,EP,GD,IN,MD,EP,NP,SMD,IN,BD,...,IN,GD,NaN,NaN,NaN,DUELISTA,NaN,NaN,NaN,NaN
"(3, Valentín, JC, ENT, EP, BD, MD, EP, AD)",MD,EG,IN,SMD,EG,IN,BD,BD,BD,DG,...,None,EL,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(4, Aitana, JC, ENT, EP, IN, MD, EG, IN)",NP,IN,MD,EG,IN,MD,BD,SMD,MD,EG,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(5, Carlos, SVN, ENT, EP, AD, BD, EG, IN)",MD,EP,IN,BD,EP,GD,IN,MD,AD,IN,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(6, Samira, PR, EL, ENT, EG, IN, MD, EP)",MD,AD,GD,GD,EG,IN,MD,EG,IN,MD,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(7, Carmen, SVN, ENT, EP, BD, SMD, EP, MD)",MD,EG,IN,MD,EG,IN,BD,BD,GD,DP,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(8, Natalia, PR, ENT, EG, IN, MD, EG, IN)",MD,EG,IN,BD,EP,NP,GD,IN,BD,BD,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(9, Gloria, JC, ENT, EP, MD, MD, EP, AD)",MD,EG,IN,MD,EP,IN,MD,AD,IN,DP,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(10, Marcos, JC, ENT, EP, AD, MD, EP, IN)",MD,EP,BD,NP,GD,BD,EP,NP,BD,GD,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(11, Osiris, PR, ENT, EG, IN, GD, EG, AD)",MD,EG,NP,GD,IN,BD,EG,IN,MD,BD,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(12, Josecho, PR, ENT, EG, IN, MD, EG, IN)",GD,EG,IN,BD,EG,IN,MD,AD,AB,None,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(13, Laly, SVN, ENT, EP, MD, MD, EP, SPD)",DP,EP,IN,GD,EP,BD,NP,EL,BD,None,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(14, Alicia, PR, ENT, EG, IN, BD, EG, IN)",DP,EP,NP,BD,EL,BD,None,None,None,None,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(15, Sara, PR, ENT, EG, IN, MD, EP, EL)",SMD,None,None,None,None,None,None,None,None,None,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(16, Jeancha, SVN, ENT, EP, EL, BD, nan, nan)",None,None,None,None,None,None,None,None,None,None,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(1, Ana, MD)",ENT,SMD,AD,IN,AD,EG,IN,SMD,EG,IN,...,BD,GD,NaN,NaN,NaN,IN,NaN,GANADORA,SMD,IN
"(1, Arnau, ENT, EP, BD, MD)",EP,IN,GD,EP,MD,AD,IN,GD,AD,EP,...,GD,MD,NaN,NaN,NaN,IN,NaN,NaN,NaN,NaN
"(2, Meri, ENT, EG, IN, SMD)",EG,IN,AD,EG,IN,MD,NP,EP,AD,MD,...,GD,EG,NaN,NaN,NaN,DUELISTA,NaN,NaN,NaN,NaN
"(3, María, ENT, EP, SMD, GD)",EP,GD,MD,EP,MD,MD,SPD,MD,NP,EP,...,EL,EG,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(4, Fran, ENT, EG, IN, MD)",EG,IN,BD,EG,IN,MD,NP,EG,IN,MD,...,None,GD,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(5, Ofelia, ENT, EP, MD, MD)",EP,MD,MD,EP,AD,IN,SMD,AD,EG,IN,...,None,SPD,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(6, José, AB, ENT, SMD, EP)",NP,AD,IN,MD,EG,IN,BD,EP,SPD,MD,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(7, Toni, ENT, EP, IN, MD)",EP,BD,BD,EG,IN,MD,NP,NP,IN,DG,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(8, Amelicious, ENT, EP, GD, AD)",EG,IN,SMD,EG,IN,MD,NP,EG,IN,MD,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(9, Jiaping, ENT, EG, IN, MD)",EP,BD,AD,EG,IN,MD,NP,EG,IN,DP,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(10, Dani, ENT, EG, IN, MD)",EG,IN,AD,EP,AD,IN,MD,NP,EP,MD,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(11, Pepe, ENT, EG, IN, MD)",EG,IN,MD,EG,IN,MD,NP,EG,AD,MD,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(12, Alicia, ENT, EG, IN, MD)",EP,MD,MD,EG,IN,MD,NP,EP,MD,AD,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(13, Vero, ENT, EG, IN, AD)",EG,IN,MD,EP,MD,AD,IN,MD,NP,EP,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(14, Álex, ENT, EP, BD, MD)",EG,IN,MD,EP,MD,BD,EL,BD,None,None,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(15, José, María, ENT, EG, IN)",MD,EP,EL,BD,None,None,None,None,None,None,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
"(16, Jesús, ENT, EP, EL, BD)",None,None,None,None,None,None,None,None,None,None,...,None,None,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN

In [367]:
todas_infos.to_excel(r'C:\Users\alexd\Ironhack\Proyectos\Project4_DA_Ironhack\Data\masterchef_info.xls', index=True)

C:\Users\alexd\AppData\Local\Temp/ipykernel_14416/3214401319.py:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  todas_infos.to_excel(r'C:\Users\alexd\Ironhack\Proyectos\Project4_DA_Ironhack\Data\masterchef_info.xls', index=True)

In [368]:
masterchef_info=pd.read_excel(r'C:\Users\alexd\Ironhack\Proyectos\Project4_DA_Ironhack\Data\masterchef_info.xls')

In [369]:
masterchef_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   edicion  110 non-null    int64
 1   ranking  110 non-null    int64
 2   EG       110 non-null    int64
 3   EP       110 non-null    int64
dtypes: int64(4)
memory usage: 3.6 KB

In [370]:
str_conn='mysql+pymysql://root:password@127.0.0.1:3306/project4'

cursor=create_engine(str_conn)

In [371]:
masterchef_info.to_sql(name='info', con=cursor, if_exists='replace', index=False)